---
name: W5 Variables & Secrets for Multiple Workflows

run-name: 🖐️ This workflow was executed manually by ${{ github.actor }}

on: workflow_dispatch

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: Greet NOC
        run: |
          echo "${{ vars.GREETING }} NOC"
          echo "${{ secrets.ENCRYPTED_GREETING }} NOC"
  