name: W7 Environments, variables & secrets hierarchy

run-name: 🖐️ This workflow was executed manually by ${{ github.actor }}

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run workflow against'
        type: environment
        required: false

jobs:
  greeting-environments:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Greting DEV
        if: ${{ inputs.environment == 'DEV' }}
        run: |
          echo "${{ vars.GREETING }} NOC"
      - name: Greting PRE
        if: ${{ inputs.environment == 'PRE' }}
        run: |
          echo "${{ vars.GREETING }} NOC"
      - name: Greting PROD
        if: ${{ inputs.environment == 'PROD' }}
        run: |
          echo "${{ vars.GREETING }} NOC"
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greting
        run: |
          echo "${{ vars.GREETING }} NOC"
